#!/usr/bin/env bash
# idk what is it?
i=1
while (( i < 101 )); do
	if (( i % 3 == 0 && i % 5 == 0 )); then
		echo "FizzBuzz"
	elif (( i % 3 == 0); then
		echo "Fizz"
	elif (( i % 5 == 0); then
		echo "Buzz"
	else
		echo "$i";fi
	fi
	((i++))
done
