#!/usr/bin/env bash
# 11-read_and_cut (alternative)

while read -r line; do
    user=$(echo "$line" | cut -d: -f1)
    uid=$(echo "$line"  | cut -d: -f3)
    home=$(echo "$line" | cut -d: -f6)
    echo "$user:$uid:$home"
done < /etc/passwd
