#!/usr/bin/env bash
# 10-process_and_pid_file

PIDFILE="/var/run/myscript.pid"

printf '%s\n' "$$" | sudo tee "$PIDFILE" > /dev/null

on_term() {
    echo "I hate the kill command"
    # sudo rm -f "$PIDFILE"
    exit 0
}

on_int() {
    echo "Y U no love me?!"
    exit 130
}

on_quit() {
    # sudo rm -f "$PIDFILE"
    exit 0
}

trap 'on_term' TERM
trap 'on_int' INT
trap 'on_quit' QUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
