#!/usr/bin/env bash
# asdadasd
# shellcheck disable=SC2024
PIDFILE="./var/run/myscript.pid"

trap 'echo I hate the kill command; rm -f "$PIDFILE"' TERM
trap 'echo Y U no love me?!' INT
trap 'rm -f "$PIDFILE"' QUIT

echo "$$" > "$PIDFILE"

while true; do
	echo "To infinity and beyond"
done
